/-
Copyright (c) 2026 Michail Karatarakis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michail Karatarakis
-/
module

public import Mathlib.Analysis.RCLike.Basic
public import Mathlib.Analysis.SpecialFunctions.Trigonometric.Inverse
public import Mathlib.Data.Nat.Choose.Basic
public import Mathlib.LinearAlgebra.Matrix.GivensRotation

/-!
# Factorization of unitary matrices into Givens rotations

Over an `RCLike` field `𝕜` (i.e. `ℝ` or `ℂ`), Givens rotations can eliminate entries of vectors
and matrices while staying in the unitary group. We prove the elimination step and deduce that
every unitary matrix is a product of Givens rotations and a diagonal unitary matrix
([horn2013], Section 2.1). This parallels the reduction of arbitrary matrices to diagonal form
by transvections in `Mathlib/LinearAlgebra/Matrix/Transvection.lean`.

## Main results

* `Matrix.exists_givensRotation_coeffs` : the basic elimination step; for `a b : 𝕜` there are
  Givens coefficients whose rotation sends the vector `![a, b]` to a vector supported in the
  first coordinate.
* `Matrix.GivensRotationStruct.exists_list_toMatrix_prod_mulVec_eq_zero` : any vector can be
  concentrated into a single coordinate by a product of Givens rotations.
* `Matrix.GivensRotationStruct.exists_prod_mul_eq_diagonal` : for any unitary matrix `U` there
  is a list `L` of Givens rotations such that `(L.map toMatrix).prod * U` is a unitary diagonal
  matrix. This is the QR factorization of a unitary matrix by Givens rotations.
* `Matrix.GivensRotationStruct.exists_eq_prod_mul_diagonal` : any unitary matrix is a product
  of Givens rotations and a unitary diagonal matrix. In the physics literature this
  factorization (for `𝕜 = ℂ`) underlies the Reck decomposition of a linear optical
  interferometer into a mesh of beam splitters and phase shifters.
* `Matrix.GivensRotationStruct.unitary_induction` : the induction principle stating that the
  unitary group is generated by Givens rotations and unitary diagonal matrices.
* `Matrix.GivensRotationStruct.ofAngle` : the Givens rotation by a real angle `θ`, with
  `c = cos θ` and `s = sin θ`. Over `ℝ`, every Givens rotation is of this form
  (`Matrix.GivensRotationStruct.exists_cos_eq_and_sin_eq`), and consequently every element of
  `SU(2, ℝ) = SO(2)` is a rotation by an angle
  (`Matrix.mem_specialUnitaryGroup_fin_two_iff_exists_angle`).

## Implementation notes

The proof of the factorization is by induction on the size of the matrix, mirroring
`Mathlib/LinearAlgebra/Matrix/Transvection.lean`: the inductive step works with matrices
indexed by `Fin r ⊕ Unit`, where Givens rotations in the planes `(inl k, inr unit)` are used to
empty the last column of the matrix; unitarity then forces the last row to vanish as well, so
that the matrix is block diagonal and the inductive hypothesis applies. A reindexing argument
transfers the result to arbitrary finite index types.
-/

@[expose] public section

namespace Matrix

open Sum

variable {𝕜 : Type*} [RCLike 𝕜]

open ComplexConjugate in
/-- The scalar elimination step for Givens rotations: given `a b : 𝕜`, there are coefficients
`c`, `s` of a Givens rotation whose associated rotation of `𝕜²` maps the vector `![a, b]` to a
vector with vanishing second coordinate. -/
theorem exists_givensRotation_coeffs (a b : 𝕜) :
    ∃ c s : 𝕜, c * star c + s * star s = 1 ∧ -star s * a + star c * b = 0 := by
  by_cases h : a = 0 ∧ b = 0
  · exact ⟨1, 0, by simp, by simp [h.1, h.2]⟩
  have hpos : 0 < ‖a‖ ^ 2 + ‖b‖ ^ 2 := by
    rcases not_and_or.mp h with h | h
    · exact add_pos_of_pos_of_nonneg (pow_pos (norm_pos_iff.mpr h) 2) (by positivity)
    · exact add_pos_of_nonneg_of_pos (by positivity) (pow_pos (norm_pos_iff.mpr h) 2)
  set r : ℝ := √(‖a‖ ^ 2 + ‖b‖ ^ 2) with hrdef
  have hr0 : (r : 𝕜) ≠ 0 := RCLike.ofReal_ne_zero.mpr (Real.sqrt_ne_zero'.mpr hpos)
  have hrr : (r : 𝕜) * r = conj a * a + conj b * b := by
    rw [RCLike.conj_mul, RCLike.conj_mul, ← RCLike.ofReal_mul, hrdef,
      Real.mul_self_sqrt hpos.le]
    push_cast
    ring
  refine ⟨star a / r, star b / r, ?_, ?_⟩
  · simp only [RCLike.star_def, map_div₀, RCLike.conj_conj, RCLike.conj_ofReal,
      div_mul_div_comm, ← add_div, ← hrr]
    exact div_self (mul_ne_zero hr0 hr0)
  · simp only [RCLike.star_def, map_div₀, RCLike.conj_conj, RCLike.conj_ofReal]
    ring

namespace GivensRotationStruct

section Angle

variable {n : Type*} [DecidableEq n] {i j : n}

/-- The Givens rotation in the `(i, j)`-plane by the real angle `θ`, as a
`GivensRotationStruct` over `𝕜`. -/
@[simps]
noncomputable def ofAngle (hij : i ≠ j) (θ : ℝ) : GivensRotationStruct n 𝕜 where
  i := i
  j := j
  hij := hij
  c := (Real.cos θ : 𝕜)
  s := (Real.sin θ : 𝕜)
  norm_eq := by
    rw [RCLike.star_def, RCLike.conj_ofReal, RCLike.conj_ofReal]
    norm_cast
    linear_combination Real.sin_sq_add_cos_sq θ

omit [DecidableEq n] in
/-- Over `ℝ`, every Givens rotation is a rotation by an angle. -/
theorem exists_cos_eq_and_sin_eq (g : GivensRotationStruct n ℝ) :
    ∃ θ : ℝ, Real.cos θ = g.c ∧ Real.sin θ = g.s :=
  Real.exists_cos_eq_and_sin_eq (by simpa [sq] using g.norm_eq)

end Angle

/-- Every element of `SU(2, ℝ) = SO(2)` is a plane rotation by an angle. -/
theorem _root_.Matrix.mem_specialUnitaryGroup_fin_two_iff_exists_angle
    {U : Matrix (Fin 2) (Fin 2) ℝ} :
    U ∈ specialUnitaryGroup (Fin 2) ℝ ↔
      ∃ θ : ℝ, U = givensRotation 0 1 (Real.cos θ) (Real.sin θ) := by
  rw [mem_specialUnitaryGroup_fin_two_iff_exists_givensRotation]
  constructor
  · rintro ⟨c, s, h, rfl⟩
    obtain ⟨θ, hc, hs⟩ := Real.exists_cos_eq_and_sin_eq (by simpa [sq] using h)
    exact ⟨θ, by rw [hc, hs]⟩
  · rintro ⟨θ, rfl⟩
    exact ⟨_, _, by simpa [sq] using Real.cos_sq_add_sin_sq θ, rfl⟩

section Elimination

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- Given two indices `i ≠ j` and a vector `v`, there is a Givens rotation in the `(i, j)`-plane
killing the `j`-th coordinate of `v`. -/
theorem exists_toMatrix_mulVec_apply_eq_zero {i j : n} (hij : i ≠ j) (v : n → 𝕜) :
    ∃ g : GivensRotationStruct n 𝕜, g.i = i ∧ g.j = j ∧ g.toMatrix.mulVec v j = 0 := by
  obtain ⟨c, s, h1, h2⟩ := exists_givensRotation_coeffs (v i) (v j)
  exact ⟨⟨i, j, hij, c, s, h1⟩, rfl, rfl, by simpa [hij] using h2⟩

/-- Any vector can be concentrated into the single coordinate `t` by a product of fewer than
`Fintype.card n` Givens rotations. -/
theorem exists_list_toMatrix_prod_mulVec_eq_zero (t : n) (v : n → 𝕜) :
    ∃ L : List (GivensRotationStruct n 𝕜), L.length < Fintype.card n ∧
      ∀ k, k ≠ t → ((L.map toMatrix).prod).mulVec v k = 0 := by
  suffices H : ∀ S : Finset n, t ∉ S → ∀ v : n → 𝕜,
      ∃ L : List (GivensRotationStruct n 𝕜), L.length ≤ S.card ∧
        (∀ k ∈ S, ((L.map toMatrix).prod).mulVec v k = 0) ∧
        ∀ k, k ∉ S → k ≠ t → ((L.map toMatrix).prod).mulVec v k = v k by
    obtain ⟨L, hlen, hL, -⟩ := H (Finset.univ.erase t) (Finset.notMem_erase t _) v
    refine ⟨L, ?_, fun k hk => hL k (Finset.mem_erase.mpr ⟨hk, Finset.mem_univ k⟩)⟩
    have h₁ : 0 < Fintype.card n := Fintype.card_pos_iff.mpr ⟨t⟩
    simp only [Finset.card_erase_of_mem (Finset.mem_univ t), Finset.card_univ] at hlen
    omega
  intro S
  induction S using Finset.induction_on with
  | empty => exact fun _ v => ⟨[], le_rfl, by simp, by simp⟩
  | insert a S haS IH =>
    intro ht v
    obtain ⟨hta, htS⟩ : t ≠ a ∧ t ∉ S := by simpa [not_or] using ht
    obtain ⟨g, hgi, hgj, hg0⟩ := exists_toMatrix_mulVec_apply_eq_zero hta v
    obtain ⟨L, hlen, hL1, hL2⟩ := IH htS (g.toMatrix.mulVec v)
    have hprod : (((L ++ [g]).map toMatrix).prod).mulVec v =
        ((L.map toMatrix).prod).mulVec (g.toMatrix.mulVec v) := by
      simp [mulVec_mulVec]
    refine ⟨L ++ [g], ?_, fun k hk => ?_, fun k hk hkt => ?_⟩
    · simpa [Finset.card_insert_of_notMem haS] using Nat.add_le_add_right hlen 1
    · rw [hprod]
      rcases Finset.mem_insert.mp hk with rfl | hkS
      · rw [hL2 k haS hta.symm, hg0]
      · exact hL1 k hkS
    · obtain ⟨hka, hkS⟩ : k ≠ a ∧ k ∉ S := by simpa [not_or] using hk
      rw [hprod, hL2 k hkS hkt]
      exact g.toMatrix_mulVec_of_ne (by rw [hgi]; exact hkt) (by rw [hgj]; exact hka) v

end Elimination

section Factorization

/-- The key step of the factorization of unitary matrices: over `Fin r ⊕ Unit`, Givens
rotations reduce a unitary matrix to a block diagonal one, with a `1 × 1` unitary block in the
corner. -/
theorem exists_prod_mul_eq_fromBlocks {r : ℕ}
    {U : Matrix (Fin r ⊕ Unit) (Fin r ⊕ Unit) 𝕜} (hU : U ∈ unitaryGroup (Fin r ⊕ Unit) 𝕜) :
    ∃ (L : List (GivensRotationStruct (Fin r ⊕ Unit) 𝕜)) (V : Matrix (Fin r) (Fin r) 𝕜)
      (u : 𝕜), L.length ≤ r ∧ V ∈ unitaryGroup (Fin r) 𝕜 ∧ u ∈ unitary 𝕜 ∧
        (L.map toMatrix).prod * U = fromBlocks V 0 0 (diagonal fun _ => u) := by
  obtain ⟨L, hlen, hL⟩ :=
    exists_list_toMatrix_prod_mulVec_eq_zero (inr ()) fun k => U k (inr ())
  set W : Matrix (Fin r ⊕ Unit) (Fin r ⊕ Unit) 𝕜 := (L.map toMatrix).prod * U with hWdef
  have hWmem : W ∈ unitaryGroup (Fin r ⊕ Unit) 𝕜 :=
    mul_mem (toMatrix_prod_mem_unitaryGroup L) hU
  have hcol : ∀ k : Fin r, W (inl k) (inr ()) = 0 := fun k => by
    simpa [hWdef, mul_apply, mulVec, dotProduct] using hL (inl k) (by simp)
  have h1 := mem_unitaryGroup_iff'.mp hWmem
  have huu : star (W (inr ()) (inr ())) * W (inr ()) (inr ()) = 1 := by
    simpa [mul_apply, Fintype.sum_sum_type, star_apply, hcol] using
      congrFun (congrFun h1 (inr ())) (inr ())
  have hrow : ∀ k : Fin r, W (inr ()) (inl k) = 0 := fun k => by
    have h := congrFun (congrFun h1 (inr ())) (inl k)
    simp only [mul_apply, Fintype.sum_sum_type, star_apply, hcol, star_zero, zero_mul,
      Finset.sum_const_zero, zero_add, Finset.univ_unique, PUnit.default_eq_unit,
      Finset.sum_singleton, one_apply, reduceCtorEq, if_false] at h
    linear_combination W (inr ()) (inr ()) * h - W (inr ()) (inl k) * huu
  have hW : W = fromBlocks W.toBlocks₁₁ 0 0 (diagonal fun _ => W (inr ()) (inr ())) := by
    ext (a | ⟨⟩) (b | ⟨⟩) <;> simp [toBlocks₁₁, hcol, hrow]
  exact ⟨L, W.toBlocks₁₁, W (inr ()) (inr ()), by simpa [Nat.lt_succ_iff] using hlen,
    (fromBlocks_mem_unitaryGroup_iff.mp (hW ▸ hWmem)).1,
    ⟨huu, by rw [mul_comm]; exact huu⟩, hWdef.symm.trans hW⟩

/-- Inductive step for the factorization of unitary matrices: if every unitary matrix of size
`r` is a product of Givens rotations and a unitary diagonal matrix, then the same holds for
unitary matrices over `Fin r ⊕ Unit`. -/
theorem exists_prod_mul_eq_diagonal_induction {r : ℕ}
    (IH : ∀ V : Matrix (Fin r) (Fin r) 𝕜, V ∈ unitaryGroup (Fin r) 𝕜 →
      ∃ (L : List (GivensRotationStruct (Fin r) 𝕜)) (d : Fin r → 𝕜),
        L.length ≤ (Fintype.card (Fin r)).choose 2 ∧
        (∀ i, d i ∈ unitary 𝕜) ∧ (L.map toMatrix).prod * V = diagonal d)
    {U : Matrix (Fin r ⊕ Unit) (Fin r ⊕ Unit) 𝕜} (hU : U ∈ unitaryGroup (Fin r ⊕ Unit) 𝕜) :
    ∃ (L : List (GivensRotationStruct (Fin r ⊕ Unit) 𝕜)) (d : Fin r ⊕ Unit → 𝕜),
      L.length ≤ (Fintype.card (Fin r ⊕ Unit)).choose 2 ∧
      (∀ i, d i ∈ unitary 𝕜) ∧ (L.map toMatrix).prod * U = diagonal d := by
  obtain ⟨L₁, V, u, hlen₁, hV, hu, hL₁⟩ := exists_prod_mul_eq_fromBlocks hU
  obtain ⟨L₀, d₀, hlen₀, hd₀, h₀⟩ := IH V hV
  refine ⟨L₀.map (sumInl Unit) ++ L₁, Sum.elim d₀ fun _ => u, ?_, ?_, ?_⟩
  · have hcard : Fintype.card (Fin r ⊕ Unit) = r + 1 := by simp
    have hchoose : (r + 1).choose 2 = r + r.choose 2 := by
      rw [Nat.choose_succ_succ, Nat.choose_one_right]
    rw [Fintype.card_fin] at hlen₀
    rw [List.length_append, List.length_map, hcard, hchoose]
    omega
  · rintro (i | i)
    · exact hd₀ i
    · exact hu
  · rw [List.map_append, List.prod_append, Matrix.mul_assoc, hL₁, List.map_map,
      sumInl_toMatrix_prod_mul, h₀, fromBlocks_diagonal]

/-- Reduction of a unitary matrix to diagonal form by Givens rotations is invariant under
reindexing. -/
theorem reindex_exists_prod_mul_eq_diagonal {n p : Type*} [Fintype n] [DecidableEq n]
    [Fintype p] [DecidableEq p] (U : Matrix p p 𝕜) (e : p ≃ n)
    (H : ∃ (L : List (GivensRotationStruct n 𝕜)) (d : n → 𝕜),
      L.length ≤ (Fintype.card n).choose 2 ∧
      (∀ i, d i ∈ unitary 𝕜) ∧ (L.map toMatrix).prod * reindexAlgEquiv 𝕜 _ e U = diagonal d) :
    ∃ (L : List (GivensRotationStruct p 𝕜)) (d : p → 𝕜),
      L.length ≤ (Fintype.card p).choose 2 ∧
      (∀ i, d i ∈ unitary 𝕜) ∧ (L.map toMatrix).prod * U = diagonal d := by
  obtain ⟨L₀, d₀, hlen₀, hd₀, h₀⟩ := H
  refine ⟨L₀.map (reindexEquiv e.symm), d₀ ∘ e,
    by rwa [List.length_map, Fintype.card_congr e], fun i => hd₀ (e i), ?_⟩
  simpa [List.map_map, toMatrix_reindexEquiv_prod, map_mul, reindexAlgEquiv_apply,
    reindex_apply, submatrix_submatrix, Equiv.symm_comp_self, submatrix_id_id,
    submatrix_diagonal_equiv] using congrArg (reindexAlgEquiv 𝕜 _ e.symm) h₀

/-- Any unitary matrix over `Type`-valued indices can be reduced to a unitary diagonal matrix
by Givens rotations. Formulated on `Type 0` for the inductive argument; see
`Matrix.GivensRotationStruct.exists_prod_mul_eq_diagonal` for the general version. -/
theorem exists_prod_mul_eq_diagonal_aux (n : Type) [Fintype n] [DecidableEq n]
    (U : Matrix n n 𝕜) (hU : U ∈ unitaryGroup n 𝕜) :
    ∃ (L : List (GivensRotationStruct n 𝕜)) (d : n → 𝕜),
      L.length ≤ (Fintype.card n).choose 2 ∧
      (∀ i, d i ∈ unitary 𝕜) ∧ (L.map toMatrix).prod * U = diagonal d := by
  suffices ∀ (r : ℕ) (n : Type) [Fintype n] [DecidableEq n], Fintype.card n = r →
      ∀ U : Matrix n n 𝕜, U ∈ unitaryGroup n 𝕜 →
        ∃ (L : List (GivensRotationStruct n 𝕜)) (d : n → 𝕜),
          L.length ≤ (Fintype.card n).choose 2 ∧
          (∀ i, d i ∈ unitary 𝕜) ∧ (L.map toMatrix).prod * U = diagonal d by
    exact this _ n rfl U hU
  intro r
  induction r with
  | zero =>
    intro n _ _ hn U _
    haveI := Fintype.card_eq_zero_iff.mp hn
    exact ⟨[], fun _ => 1, Nat.zero_le _, fun i => isEmptyElim i,
      by ext i j; exact isEmptyElim i⟩
  | succ r IH =>
    intro n _ _ hn U hU
    have e : n ≃ Fin r ⊕ Unit := Fintype.equivOfCardEq (by simp [hn])
    exact reindex_exists_prod_mul_eq_diagonal U e
      (exists_prod_mul_eq_diagonal_induction (fun V hV => IH (Fin r) (by simp) V hV)
        (reindexAlgEquiv_mem_unitaryGroup e hU))

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- **Factorization of unitary matrices by Givens rotations**, elimination form: for every
unitary matrix `U` over an index type of cardinality `N` there are at most `N.choose 2`
Givens rotations whose product reduces `U` to a unitary diagonal matrix. This is the QR
factorization of a unitary matrix, and `N.choose 2 = N * (N - 1) / 2` is the size of the Reck
mesh. -/
theorem exists_prod_mul_eq_diagonal {U : Matrix n n 𝕜} (hU : U ∈ unitaryGroup n 𝕜) :
    ∃ (L : List (GivensRotationStruct n 𝕜)) (d : n → 𝕜),
      L.length ≤ (Fintype.card n).choose 2 ∧
      (∀ i, d i ∈ unitary 𝕜) ∧ (L.map toMatrix).prod * U = diagonal d := by
  have e : n ≃ Fin (Fintype.card n) := Fintype.equivOfCardEq (by simp)
  exact reindex_exists_prod_mul_eq_diagonal U e
    (exists_prod_mul_eq_diagonal_aux _ _ (reindexAlgEquiv_mem_unitaryGroup e hU))

/-- **Factorization of unitary matrices by Givens rotations**: every unitary matrix over an
index type of cardinality `N` is a product of at most `N.choose 2 = N * (N - 1) / 2` Givens
rotations and a unitary diagonal matrix. For `𝕜 = ℂ` this is the Reck decomposition of linear
optics, and `N.choose 2` is the number of beam splitters in the mesh. -/
theorem exists_eq_prod_mul_diagonal {U : Matrix n n 𝕜} (hU : U ∈ unitaryGroup n 𝕜) :
    ∃ (L : List (GivensRotationStruct n 𝕜)) (d : n → 𝕜),
      L.length ≤ (Fintype.card n).choose 2 ∧
      (∀ i, d i ∈ unitary 𝕜) ∧ U = (L.map toMatrix).prod * diagonal d := by
  obtain ⟨L, d, hlen, hd, hL⟩ := exists_prod_mul_eq_diagonal hU
  refine ⟨L.reverse.map GivensRotationStruct.inv, d,
    by simpa using hlen, hd, ?_⟩
  rw [List.map_map, ← hL, ← Matrix.mul_assoc, reverse_inv_prod_mul_prod, Matrix.one_mul]

/-- Induction principle for unitary matrices based on Givens rotations: if a property is true
for all unitary diagonal matrices and all Givens rotations, and is stable under products, then
it is true for all unitary matrices. This is the useful way to say that the unitary group is
generated by Givens rotations (embedded `U(2)` blocks) and unitary diagonal matrices. -/
theorem unitary_induction (P : Matrix n n 𝕜 → Prop) {U : Matrix n n 𝕜}
    (hU : U ∈ unitaryGroup n 𝕜)
    (hdiag : ∀ d : n → 𝕜, (∀ i, d i ∈ unitary 𝕜) → P (diagonal d))
    (hgivens : ∀ g : GivensRotationStruct n 𝕜, P g.toMatrix)
    (hmul : ∀ A B, P A → P B → P (A * B)) : P U := by
  obtain ⟨L, d, -, hd, hL⟩ := exists_eq_prod_mul_diagonal hU
  rw [hL]
  clear hL hU
  induction L with
  | nil => simpa using hdiag d hd
  | cons g L IH =>
    rw [List.map_cons, List.prod_cons, Matrix.mul_assoc]
    exact hmul _ _ (hgivens g) IH

end Factorization

end GivensRotationStruct

end Matrix
