/-
Copyright (c) 2026 Michail Karatarakis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michail Karatarakis
-/
module

public import Mathlib.NumberTheory.Transcendental.Baker.Padic.Parameters

/-!
# The `p`-adic Baker theorem

**Brumer's theorem**, the `p`-adic analogue of Baker's theorem: let `ℓ i ∈ ℂ_[p]` lie in the
disc `‖z‖ < p ^ (-1 / (p - 1))` on which the exponential converges, with `exp (ℓ i)` algebraic.
If the `ℓ i` are linearly independent over `ℚ`, then `1` and the `ℓ i` are linearly independent
over the algebraic numbers (`PadicBaker.eq_zero_of_add_sum_mul_eq_zero`), and a nonzero linear
form in the `ℓ i` with algebraic coefficients is transcendental
(`PadicBaker.transcendental_add_sum_mul`).

The proof is Baker's method as in Baker–Masser, *Transcendental Number Theory*, Chapter 2,
carried out over `ℂ_[p]` in `PadicBaker.core`. Here the relation is normalised so that one
logarithm has coefficient `1`, the number field generated by the data is formed inside
`ℂ_[p]`, and the constants and parameters of `PadicBaker.core` are chosen
(`PadicBaker.exists_parameters`).

## References

* A. Brumer, *On the units of algebraic number fields*, Mathematika 14 (1967), 121–124.
* A. Baker and D. Masser, *Transcendental Number Theory*, Cambridge Mathematical Library,
  Cambridge University Press, 2022, Chapter 2.
-/

@[expose] public section

open NumberField

namespace PadicBaker

variable {p : ℕ} [hp : Fact p.Prime]

/-- **Brumer's theorem**, the `p`-adic Baker theorem: `1` and `ℚ`-linearly independent `p`-adic
logarithms of algebraic numbers are linearly independent over the algebraic numbers. -/
theorem eq_zero_of_add_sum_mul_eq_zero {ι : Type*} [Fintype ι] {ℓ : ι → ℂ_[p]}
    (hsmall : ∀ i, ‖ℓ i‖ < (p : ℝ) ^ (-((p : ℝ) - 1)⁻¹))
    (halg : ∀ i, IsAlgebraic ℚ (NormedSpace.exp (ℓ i))) (hli : LinearIndependent ℚ ℓ)
    {β₀ : ℂ_[p]} {β : ι → ℂ_[p]} (hβ₀ : IsAlgebraic ℚ β₀) (hβ : ∀ i, IsAlgebraic ℚ (β i))
    (hrel : β₀ + ∑ i, β i * ℓ i = 0) : β₀ = 0 ∧ ∀ i, β i = 0 := by
  classical
  by_cases hall : ∀ i, β i = 0
  · exact ⟨by simpa [hall] using hrel, hall⟩
  exfalso
  push Not at hall
  obtain ⟨i₀, hi₀⟩ := hall
  -- the logarithm `ℓ i₀` gets the coefficient `1`
  set k := Fintype.card {i // i ≠ i₀}
  set σ : Option (Fin k) ≃ ι :=
    (Equiv.optionCongr (Fintype.equivFin _).symm).trans (Equiv.optionSubtypeNe i₀) with hσ
  have hσ0 : σ none = i₀ := rfl
  have hrel' : ℓ (σ none) = -β₀ / β i₀ +
      ∑ r, -β (σ (some r)) / β i₀ * ℓ (σ (some r)) := by
    rw [← σ.sum_comp, Fintype.sum_option, hσ0] at hrel
    have hsum : ∑ r, -β (σ (some r)) / β i₀ * ℓ (σ (some r)) =
        -(∑ r, β (σ (some r)) * ℓ (σ (some r))) / β i₀ := by
      rw [neg_div, Finset.sum_div, ← Finset.sum_neg_distrib]
      refine Finset.sum_congr rfl fun r _ => ?_
      ring
    rw [hsum, hσ0]
    field_simp
    linear_combination hrel
  -- the number field generated by the data
  set T : Set ℂ_[p] := Set.range (fun i => NormedSpace.exp (ℓ i)) ∪ Set.range β ∪ {β₀} with hT
  have hTfin : T.Finite :=
    ((Set.finite_range _).union (Set.finite_range _)).union (Set.finite_singleton _)
  have : Finite T := hTfin.to_subtype
  have hTalg : ∀ z ∈ T, IsAlgebraic ℚ z := by
    rintro z ((⟨i, rfl⟩ | ⟨i, rfl⟩) | hz)
    · exact halg i
    · exact hβ i
    · rw [Set.mem_singleton_iff.mp hz]; exact hβ₀
  set K := IntermediateField.adjoin ℚ T with hK
  have : FiniteDimensional ℚ K :=
    IntermediateField.finiteDimensional_adjoin fun z hz => (hTalg z hz).isIntegral
  have : NumberField K := ⟨⟩
  have hmem : ∀ z ∈ T, z ∈ K := fun z hz => IntermediateField.subset_adjoin ℚ T hz
  set αK : Option (Fin k) → K := fun o =>
    ⟨NormedSpace.exp (ℓ (σ o)), hmem _ (Or.inl (Or.inl ⟨σ o, rfl⟩))⟩ with hαK
  set γ : ι → K := fun i => ⟨β i, hmem _ (Or.inl (Or.inr ⟨i, rfl⟩))⟩ with hγ
  set γ₀ : K := ⟨β₀, hmem _ (Or.inr rfl)⟩ with hγ₀
  set βK : Fin k → K := fun r => -γ (σ (some r)) / γ i₀ with hβK
  set βK₀ : K := -γ₀ / γ i₀ with hβK₀
  set ιK : K →+* ℂ_[p] := (IntermediateField.val K).toRingHom with hιK
  have hα : ∀ o, ιK (αK o) = NormedSpace.exp (ℓ (σ o)) := fun o => rfl
  have hβι : ∀ r, ιK (βK r) = -β (σ (some r)) / β i₀ := fun r => by
    simp only [hβK, map_div₀, map_neg]; rfl
  have hβ₀ι : ιK βK₀ = -β₀ / β i₀ := by
    simp only [hβK₀, map_div₀, map_neg]; rfl
  -- a common denominator and a bound for the houses
  set gens : Finset K := (Finset.univ.image αK ∪ Finset.univ.image βK) ∪ {βK₀} with hgens
  obtain ⟨c, hc0, hc⟩ := exists_integral_multiples ℤ ℚ (L := K) gens
  set δ : ℕ := c.natAbs with hδdef
  have hδ : 1 ≤ δ := Nat.one_le_iff_ne_zero.2 (Int.natAbs_ne_zero.2 hc0)
  have hint : ∀ g ∈ gens, IsIntegral ℤ ((δ : K) ^ 1 * g) := by
    intro g hg
    have h1 := hc g hg
    rw [pow_one]
    rcases Int.natAbs_eq c with h | h
    · have : (δ : K) * g = c • g := by
        rw [zsmul_eq_mul, hδdef,
          show ((c.natAbs : ℕ) : K) = (((c.natAbs : ℕ) : ℤ) : K) from (Int.cast_natCast _).symm,
          ← h]
      rw [this]
      exact h1
    · have : (δ : K) * g = -(c • g) := by
        rw [zsmul_eq_mul, hδdef, ← neg_mul,
          show ((c.natAbs : ℕ) : K) = (((c.natAbs : ℕ) : ℤ) : K) from (Int.cast_natCast _).symm,
          show ((c.natAbs : ℕ) : ℤ) = -c by omega, Int.cast_neg]
      rw [this]
      exact h1.neg
  set G : ℝ := δ + 1 + ∑ g ∈ gens, house ((δ : K) ^ 1 * g) with hGdef
  have hsum0 : 0 ≤ ∑ g ∈ gens, house ((δ : K) ^ 1 * g) :=
    Finset.sum_nonneg fun g _ => house_nonneg _
  have hGδ : (δ : ℝ) ≤ G := by linarith
  have hG1 : 1 ≤ G := by
    have : (1 : ℝ) ≤ δ := by exact_mod_cast hδ
    linarith
  have hsize : ∀ g ∈ gens, AlgSize δ g 1 G := fun g hg =>
    ⟨by convert hint g hg; exact Subsingleton.elim _ _, by
      have := Finset.single_le_sum (fun g _ => house_nonneg ((δ : K) ^ 1 * g)) hg
      have : (0 : ℝ) ≤ δ := Nat.cast_nonneg δ
      linarith⟩
  have hαs : ∀ o, AlgSize δ (αK o) 1 G := fun o => hsize _ (by simp [hgens])
  have hβs : ∀ r, AlgSize δ (βK r) 1 G := fun r => hsize _ (by simp [hgens])
  have hβ₀s : AlgSize δ βK₀ 1 G := hsize _ (by simp [hgens])
  obtain ⟨C, hC, hsiegel⟩ := exists_siegel K
  -- the radii
  have hli' : LinearIndependent ℚ fun o => ℓ (σ o) := hli.comp σ σ.injective
  have hℓ0 : ∀ o, 0 < ‖ℓ (σ o)‖ := fun o => norm_pos_iff.mpr (hli'.ne_zero o)
  obtain ⟨o₁, ho₁⟩ := Finite.exists_max fun o => ‖ℓ (σ o)‖
  obtain ⟨o₂, ho₂⟩ := Finite.exists_min fun o => ‖ℓ (σ o)‖
  set ρ : ℝ := (p : ℝ) ^ (-((p : ℝ) - 1)⁻¹) with hρ
  have hρ1 : ρ ≤ 1 :=
    Real.rpow_le_one_of_one_le_of_nonpos (by exact_mod_cast hp.out.one_le)
      (neg_nonpos.mpr (inv_nonneg.mpr (by
        have : (1 : ℝ) ≤ p := by exact_mod_cast hp.out.one_le
        linarith)))
  set r₀ : ℝ := ρ / ‖ℓ (σ o₁)‖ with hr₀def
  have hr₀ : 1 < r₀ := (one_lt_div (hℓ0 o₁)).mpr (hsmall _)
  have hℓr : ∀ o, ‖ℓ (σ o)‖ * r₀ ≤ ρ := fun o => by
    calc ‖ℓ (σ o)‖ * r₀ ≤ ‖ℓ (σ o₁)‖ * r₀ :=
          mul_le_mul_of_nonneg_right (ho₁ o) (zero_le_one.trans hr₀.le)
      _ = ρ := by rw [hr₀def]; field_simp [(hℓ0 o₁).ne']
  set B : ℝ := 1 + ‖-β₀ / β i₀‖ + ∑ r, ‖-β (σ (some r)) / β i₀‖ with hBdef
  have hBsum : 0 ≤ ∑ r, ‖-β (σ (some r)) / β i₀‖ := Finset.sum_nonneg fun _ _ => norm_nonneg _
  have hB : 1 ≤ B := by have := norm_nonneg (-β₀ / β i₀); linarith
  have hβB : ∀ r, ‖-β (σ (some r)) / β i₀‖ ≤ B := fun r => by
    have := Finset.single_le_sum (fun r _ => norm_nonneg (-β (σ (some r)) / β i₀))
      (Finset.mem_univ r)
    have := norm_nonneg (-β₀ / β i₀)
    linarith
  have hβ₀B : ‖-β₀ / β i₀‖ ≤ B := by linarith
  -- the parameters, and the contradiction
  obtain ⟨L, h, Kmax, S, R, hL, hh, hcount, hS0, hR0, hSstep, hext, hfin⟩ :=
    exists_parameters k (Module.finrank ℚ K) p (G := G) (C := C) hr₀ (zero_le_one.trans hB)
      (zero_le_one.trans hG1) (zero_le_one.trans hC) (hℓ0 o₂)
  exact core (ℓ := fun o => ℓ (σ o)) hrel' (fun o => hsmall _) hli' ιK hα hβι hβ₀ι hδ hGδ hG1
    hαs hβs hβ₀s hC hsiegel hr₀ hℓr hB hβB hβ₀B (hℓ0 o₂) ((hsmall _).le.trans hρ1) ho₂ hL hh
    hcount hS0 hR0 hSstep hext hfin

/-- **Baker's theorem over `ℂ_[p]`**: a linear form in `ℚ`-linearly independent `p`-adic
logarithms of algebraic numbers, with algebraic coefficients not all zero, is transcendental. -/
theorem transcendental_add_sum_mul {ι : Type*} [Fintype ι] {ℓ : ι → ℂ_[p]}
    (hsmall : ∀ i, ‖ℓ i‖ < (p : ℝ) ^ (-((p : ℝ) - 1)⁻¹))
    (halg : ∀ i, IsAlgebraic ℚ (NormedSpace.exp (ℓ i))) (hli : LinearIndependent ℚ ℓ)
    {β₀ : ℂ_[p]} {β : ι → ℂ_[p]} (hβ₀ : IsAlgebraic ℚ β₀) (hβ : ∀ i, IsAlgebraic ℚ (β i))
    (hne : ∃ i, β i ≠ 0) : Transcendental ℚ (β₀ + ∑ i, β i * ℓ i) := by
  intro hΛ
  obtain ⟨i, hi⟩ := hne
  exact hi ((eq_zero_of_add_sum_mul_eq_zero hsmall halg hli (hβ₀.sub hΛ) hβ
    (by ring)).2 i)

end PadicBaker
