/-
Copyright (c) 2026 Michail Karatarakis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michail Karatarakis
-/
module

public import Mathlib.NumberTheory.NumberField.Monogenic.Localization
public import Mathlib.NumberTheory.NumberField.Monogenic.Relative
public import Mathlib.RingTheory.Localization.LocalizationLocalization

/-!
# Relative monogenicity over an arbitrary number field base

The *accompanying paper* referred to in the docstrings below is

> M. Karatarakis, *A Local Approach to Monogenity with an Application to Lenny Jones'
> Conjecture*,

which is the write-up of this development; each result it states is named in the docstring
of the declaration formalising it.

The criteria of this directory are stated at a prime *element* `π` of the base, so applied
to `𝓞 K` directly they decide monogenicity only at principal maximal ideals — that is, only
when `K` has class number one.  This file removes that restriction.

The mechanism is the one sketched in `Mathlib.NumberTheory.NumberField.Monogenic.Localization`:
monogenicity is local, and the localisation of `𝓞 K` at a maximal ideal `𝔭` is a discrete
valuation ring, whose maximal ideal *is* principal.  So the prime element that `𝔭` may fail
to provide always exists after localising, and a criterion stated with a prime element
decides the question at every maximal ideal, principal or not.

## Main results

* `NumberField.Relative.adjoin_eq_top_of_forall_maximal_localized_saturated`: if for every
  maximal ideal `𝔭` of `𝓞 K` the subalgebra generated by `θ` over `(𝓞 K)_𝔭` is `π`-saturated
  in `(𝓞 K₁)_𝔭` for every prime element `π`, then `𝓞 K[θ] = 𝓞 K₁`.  No hypothesis on the
  class number of `K`.

## Implementation notes

The instances placing `(𝓞 K)_𝔭` between `𝓞 K` and `K`, and `(𝓞 K₁)_𝔭` between `𝓞 K₁` and
`K₁`, are not global — `Localization 𝔭.primeCompl` carries no `Algebra _ K` instance on its
own — so they are built inside the proof with
`IsLocalization.localizationAlgebraOfSubmonoidLe` and
`IsFractionRing.isFractionRing_of_isDomain_of_isLocalization`.  This is why the hypotheses
of the theorem mention only the localisations themselves and the *global* generation
statement `Algebra.adjoin K {(θ : K₁)} = ⊤`: those are expressible with the ambient
instances alone.
-/

@[expose] public section

noncomputable section

open Algebra NumberField Monogenic IsLocalization

namespace NumberField.Relative

variable {K K₁ : Type*} [Field K] [NumberField K] [Field K₁] [NumberField K₁]
  [Algebra K K₁] {θ : 𝓞 K₁}

omit [NumberField K] [NumberField K₁] in
/-- The complement of a prime of `𝓞 K`, pushed into `𝓞 K₁`, avoids the zero divisors. -/
theorem algebraMapSubmonoid_primeCompl_le_nonZeroDivisors (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] :
    Algebra.algebraMapSubmonoid (𝓞 K₁) 𝔭.primeCompl ≤ nonZeroDivisors (𝓞 K₁) :=
  Submonoid.map_le_of_le_comap _ <| 𝔭.primeCompl_le_nonZeroDivisors.trans
    (nonZeroDivisors_le_comap_nonZeroDivisors_of_injective _
      (FaithfulSMul.algebraMap_injective _ _))

/-- **Relative monogenicity over an arbitrary number field base.**  Let `K ⊆ K₁` be an
extension of number fields and `θ : 𝓞 K₁` a generator of `K₁` over `K`.  If for every maximal
ideal `𝔭` of `𝓞 K` the subalgebra generated by `θ` over the localisation `(𝓞 K)_𝔭` is
`π`-saturated in `(𝓞 K₁)_𝔭` for every prime element `π` of `(𝓞 K)_𝔭`, then
`𝓞 K[θ] = 𝓞 K₁`.

**No hypothesis on the class number of `K` is required.**  The criteria of this development
produce exactly the `π`-saturation appearing here, but only at a prime *element*; over a base
of class number greater than one a maximal ideal need not have one.  After localising it
always does: `(𝓞 K)_𝔭` is a discrete valuation ring, so it is a principal ideal ring whose
only prime is a uniformiser, and `adjoin_eq_top_of_forall_prime_saturated'` applies over it.
`adjoin_eq_top_of_forall_maximal_localizedAt` then assembles the local verdicts.

Accompanying paper: the relative criterion over an arbitrary number field base, with
no class number hypothesis. -/
theorem adjoin_eq_top_of_forall_maximal_localized_saturated
    (hgen : Algebra.adjoin K {(θ : K₁)} = ⊤)
    (hsat : ∀ (𝔭 : Ideal (𝓞 K)) (h𝔭 : 𝔭.IsMaximal),
      letI := h𝔭.isPrime
      ∀ π : Localization 𝔭.primeCompl, Prime π →
        ∀ y : LocalizedAt (𝓞 K₁) 𝔭,
          algebraMap (Localization 𝔭.primeCompl) (LocalizedAt (𝓞 K₁) 𝔭) π * y ∈
              Algebra.adjoin (Localization 𝔭.primeCompl)
                {algebraMap (𝓞 K₁) (LocalizedAt (𝓞 K₁) 𝔭) θ} →
            y ∈ Algebra.adjoin (Localization 𝔭.primeCompl)
              {algebraMap (𝓞 K₁) (LocalizedAt (𝓞 K₁) 𝔭) θ}) :
    Algebra.adjoin (𝓞 K) {θ} = ⊤ := by
  refine adjoin_eq_top_of_forall_maximal_localizedAt
    (fun 𝔭 _ => IsLocalization.injective _
      (algebraMapSubmonoid_primeCompl_le_nonZeroDivisors 𝔭)) fun 𝔭 h𝔭 => ?_
  haveI := h𝔭.isPrime
  -- `(𝓞 K)_𝔭` sits between `𝓞 K` and `K`, with `K` as its fraction field
  letI : Algebra (Localization 𝔭.primeCompl) K :=
    localizationAlgebraOfSubmonoidLe _ _ 𝔭.primeCompl (nonZeroDivisors (𝓞 K))
      𝔭.primeCompl_le_nonZeroDivisors
  haveI : IsScalarTower (𝓞 K) (Localization 𝔭.primeCompl) K :=
    localization_isScalarTower_of_submonoid_le _ _ _ _ 𝔭.primeCompl_le_nonZeroDivisors
  haveI : IsFractionRing (Localization 𝔭.primeCompl) K :=
    IsFractionRing.isFractionRing_of_isDomain_of_isLocalization
      𝔭.primeCompl (Localization 𝔭.primeCompl) K
  -- `(𝓞 K₁)_𝔭` sits between `𝓞 K₁` and `K₁`, with `K₁` as its fraction field
  have hle := algebraMapSubmonoid_primeCompl_le_nonZeroDivisors (K₁ := K₁) 𝔭
  letI : Algebra (LocalizedAt (𝓞 K₁) 𝔭) K₁ :=
    localizationAlgebraOfSubmonoidLe _ _ _ (nonZeroDivisors (𝓞 K₁)) hle
  haveI : IsScalarTower (𝓞 K₁) (LocalizedAt (𝓞 K₁) 𝔭) K₁ :=
    localization_isScalarTower_of_submonoid_le _ _ _ _ hle
  haveI : IsFractionRing (LocalizedAt (𝓞 K₁) 𝔭) K₁ :=
    IsFractionRing.isFractionRing_of_isDomain_of_isLocalization
      (Algebra.algebraMapSubmonoid (𝓞 K₁) 𝔭.primeCompl) (LocalizedAt (𝓞 K₁) 𝔭) K₁
  -- `(𝓞 K)_𝔭` reaches `K₁` through `K`, compatibly with the route through `(𝓞 K₁)_𝔭`
  letI : Algebra (Localization 𝔭.primeCompl) K₁ :=
    ((algebraMap K K₁).comp (algebraMap (Localization 𝔭.primeCompl) K)).toAlgebra
  haveI : IsScalarTower (Localization 𝔭.primeCompl) K K₁ :=
    IsScalarTower.of_algebraMap_eq' rfl
  haveI : IsScalarTower (𝓞 K) (Localization 𝔭.primeCompl) K₁ :=
    IsScalarTower.of_algebraMap_eq' (by
      rw [RingHom.algebraMap_toAlgebra, RingHom.comp_assoc, ← IsScalarTower.algebraMap_eq,
        ← IsScalarTower.algebraMap_eq])
  haveI : IsScalarTower (𝓞 K) (LocalizedAt (𝓞 K₁) 𝔭) K₁ := by
    refine IsScalarTower.of_algebraMap_eq' ?_
    rw [IsScalarTower.algebraMap_eq (𝓞 K) (𝓞 K₁) (LocalizedAt (𝓞 K₁) 𝔭), ← RingHom.comp_assoc,
      ← IsScalarTower.algebraMap_eq (𝓞 K₁) (LocalizedAt (𝓞 K₁) 𝔭) K₁,
      ← IsScalarTower.algebraMap_eq]
  haveI : IsScalarTower (Localization 𝔭.primeCompl) (LocalizedAt (𝓞 K₁) 𝔭) K₁ := by
    refine IsScalarTower.of_algebraMap_eq' (IsLocalization.ringHom_ext 𝔭.primeCompl ?_)
    rw [RingHom.comp_assoc, ← IsScalarTower.algebraMap_eq, ← IsScalarTower.algebraMap_eq]
    exact IsScalarTower.algebraMap_eq (𝓞 K) (LocalizedAt (𝓞 K₁) 𝔭) K₁
  -- the generator of `K₁` over `K` is unchanged by localising
  have hgen' : Algebra.adjoin K
      {algebraMap (LocalizedAt (𝓞 K₁) 𝔭) K₁
        (algebraMap (𝓞 K₁) (LocalizedAt (𝓞 K₁) 𝔭) θ)} = ⊤ := by
    rwa [← IsScalarTower.algebraMap_apply (𝓞 K₁) (LocalizedAt (𝓞 K₁) 𝔭) K₁]
  exact adjoin_eq_top_of_forall_prime_saturated' (K := K) (L := K₁) hgen' (hsat 𝔭 h𝔭)

end NumberField.Relative
