/-
Copyright (c) 2026 Michail Karatarakis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michail Karatarakis
-/
module

public import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# The subfields generated by `ζ + c ζ⁻¹`

Let `K` be a cyclotomic field of conductor `m`, let `ζ ∈ K` be a primitive `m`-th root of
unity and let `c` be an integer.  This file studies the subfield `ℚ(ζ + c ζ⁻¹)` of `K` and
proves that, as soon as it is a *proper* subfield, its ring of integers is generated by
`ζ + c ζ⁻¹`.

The two cases of interest are `c = 1`, where `ζ + ζ⁻¹` generates the maximal real subfield,
and `c = -1`, where `ζ - ζ⁻¹` generates the subfield studied by Nakahara and Shah.

## Main results

* `IsPrimitiveRoot.mem_adjoin_int_of_isIntegral`: if `ℚ(ζ + c ζ⁻¹) ≠ K`, then every algebraic
  integer of `ℚ(ζ + c ζ⁻¹)` lies in `ℤ[ζ + c ζ⁻¹]`.

The proof is the "highest power of `ζ`" argument: if `x = ∑_{k ≤ N} a_k (ζ + c ζ⁻¹)^k` is an
algebraic integer with `a_k ∈ ℚ`, then `ζ ^ N x` is a `ℤ`-linear combination of
`1, ζ, …, ζ ^ (2 * N)`, whose top coefficient is `a_N`.  Properness of the subfield forces
`2 * N < φ m`, so this expansion happens inside the integral basis `1, ζ, …, ζ ^ (φ m - 1)`
of `ℤ[ζ]` and the top coefficient is therefore an integer.
-/

@[expose] public section

noncomputable section

open Polynomial Finset IntermediateField Module

namespace Monogenic

/-- Given `p = ∑_{k ≤ N} a_k X ^ k`, the polynomial `∑_{k ≤ N} a_k X ^ (N - k) (X ^ 2 + c) ^ k`.

If `u = ζ + c ζ⁻¹` then `ζ * u = ζ ^ 2 + c`, so evaluating this polynomial at `ζ` gives
`ζ ^ N * p(u)`: it is the polynomial expression, in `ζ` alone, of `ζ ^ N * p(u)`. -/
def shiftPoly (c : ℤ) (N : ℕ) (p : ℚ[X]) : ℚ[X] :=
  ∑ k ∈ range (N + 1), C (p.coeff k) * X ^ (N - k) * (X ^ 2 + C (c : ℚ)) ^ k

lemma monic_X_sq_add_C (c : ℤ) : (X ^ 2 + C (c : ℚ)).Monic := monic_X_pow_add_C _ two_ne_zero

lemma natDegree_X_sq_add_C (c : ℤ) : (X ^ 2 + C (c : ℚ)).natDegree = 2 :=
  natDegree_X_pow_add_C

lemma natDegree_X_sq_add_C_pow (c : ℤ) (k : ℕ) :
    ((X ^ 2 + C (c : ℚ)) ^ k).natDegree = 2 * k := by
  rw [(monic_X_sq_add_C c).natDegree_pow, natDegree_X_sq_add_C, Nat.mul_comm]

/-- Each summand of `shiftPoly c N p` has degree at most `N + k ≤ 2 * N`. -/
lemma natDegree_shiftPoly_summand_le (c : ℤ) (N k : ℕ) (p : ℚ[X]) (hkN : k ≤ N) :
    (C (p.coeff k) * X ^ (N - k) * (X ^ 2 + C (c : ℚ)) ^ k).natDegree ≤ N + k := by
  refine natDegree_mul_le.trans ?_
  have h₁ : (C (p.coeff k) * X ^ (N - k)).natDegree ≤ N - k :=
    natDegree_mul_le.trans (by simp)
  have h₂ := natDegree_X_sq_add_C_pow c k
  omega

lemma natDegree_shiftPoly_le (c : ℤ) (N : ℕ) (p : ℚ[X]) :
    (shiftPoly c N p).natDegree ≤ 2 * N := by
  refine natDegree_sum_le_of_forall_le _ _ fun k hk => ?_
  have hkN : k ≤ N := Nat.lt_succ_iff.mp (mem_range.mp hk)
  exact (natDegree_shiftPoly_summand_le c N k p hkN).trans (by omega)

lemma coeff_shiftPoly (c : ℤ) (N : ℕ) (p : ℚ[X]) :
    (shiftPoly c N p).coeff (2 * N) = p.coeff N := by
  have hd := natDegree_X_sq_add_C_pow c N
  have hlead : ((X ^ 2 + C (c : ℚ)) ^ N).coeff (2 * N) = 1 := by
    rw [← hd]; exact (monic_X_sq_add_C c).pow N
  rw [shiftPoly, finsetSum_coeff, Finset.sum_eq_single N]
  · simp only [Nat.sub_self, pow_zero, mul_one]
    rw [coeff_C_mul, hlead, mul_one]
  · intro k hk hkN
    have hkN' : k < N := lt_of_le_of_ne (Nat.lt_succ_iff.mp (mem_range.mp hk)) hkN
    exact coeff_eq_zero_of_natDegree_lt
      ((natDegree_shiftPoly_summand_le c N k p hkN'.le).trans_lt (by omega))
  · intro h
    exact absurd (mem_range.mpr (Nat.lt_succ_self N)) h

end Monogenic

namespace IsPrimitiveRoot

variable {K : Type*} [Field K] [CharZero K] {m : ℕ} [NeZero m] {ζ : K}
  [IsCyclotomicExtension {m} ℚ K] {c : ℤ} (hζ : IsPrimitiveRoot ζ m)

include hζ

omit [CharZero K] [IsCyclotomicExtension {m} ℚ K] in
lemma ne_zero' : ζ ≠ 0 := hζ.ne_zero (NeZero.ne m)

omit [CharZero K] [IsCyclotomicExtension {m} ℚ K] in
/-- The defining relation `ζ * (ζ + c ζ⁻¹) = ζ ^ 2 + c`: this is what lets a power of `ζ`
turn a polynomial in `ζ + c ζ⁻¹` into a polynomial in `ζ`. -/
lemma mul_add_int_mul_inv (c : ℤ) : ζ * (ζ + (c : K) * ζ⁻¹) = ζ ^ 2 + (c : K) := by
  have h : ζ ≠ 0 := hζ.ne_zero'
  field_simp

omit [CharZero K] [IsCyclotomicExtension {m} ℚ K] in
lemma isIntegral_inv : IsIntegral ℤ ζ⁻¹ := by
  refine ⟨X ^ m - 1, monic_X_pow_sub_C 1 (NeZero.ne m), ?_⟩
  have h : ζ⁻¹ ^ m = 1 := by rw [inv_pow, hζ.pow_eq_one, inv_one]
  simp [h]

omit [CharZero K] [IsCyclotomicExtension {m} ℚ K] in
lemma isIntegral_add_int_mul_inv (c : ℤ) : IsIntegral ℤ (ζ + (c : K) * ζ⁻¹) :=
  (hζ.isIntegral (NeZero.pos m)).add ((isIntegral_algebraMap (x := c)).mul hζ.isIntegral_inv)

omit [IsCyclotomicExtension {m} ℚ K] in
/-- Evaluating `shiftPoly c N p` at `ζ` produces `ζ ^ N * p(ζ + c ζ⁻¹)`.  This is the key
step: a polynomial expression in `ζ + c ζ⁻¹`, multiplied by `ζ ^ N`, becomes a polynomial
expression in `ζ` alone, of degree at most `2 * N`. -/
lemma aeval_shiftPoly {N : ℕ} {p : ℚ[X]} (hp : p.natDegree < N + 1) (c : ℤ) :
    aeval ζ (Monogenic.shiftPoly c N p) = ζ ^ N * aeval (ζ + (c : K) * ζ⁻¹) p := by
  rw [Monogenic.shiftPoly, map_sum, aeval_eq_sum_range' hp, Finset.mul_sum]
  refine Finset.sum_congr rfl fun k hk => ?_
  have hkN : k ≤ N := Nat.lt_succ_iff.mp (mem_range.mp hk)
  have hpow : ζ ^ (N - k) * ζ ^ k = ζ ^ N := by rw [← pow_add]; congr 1; omega
  have hzu : (ζ ^ 2 + (c : K)) ^ k = ζ ^ k * (ζ + (c : K) * ζ⁻¹) ^ k := by
    rw [← mul_pow, hζ.mul_add_int_mul_inv c]
  simp only [map_mul, map_pow, map_add, aeval_C, aeval_X, map_intCast]
  rw [hzu, Algebra.smul_def, ← hpow]
  ring

/-- Every algebraic integer of a cyclotomic field of conductor `m` is a `ℤ`-polynomial of
degree less than `φ m` evaluated at `ζ`.  This packages the integral basis
`1, ζ, …, ζ ^ (φ m - 1)` of `ℤ[ζ]` in the form used below. -/
lemma exists_intPoly_of_isIntegral {x : K} (hx : IsIntegral ℤ x) :
    ∃ f : ℤ[X], f.natDegree < m.totient ∧ aeval ζ f = x := by
  have hIC := IsCyclotomicExtension.Rat.isIntegralClosure_adjoin_singleton (K := K) (n := m) hζ
  obtain ⟨y, hy⟩ := (IsIntegralClosure.isIntegral_iff (A := Algebra.adjoin ℤ ({ζ} : Set K))).mp hx
  have hmem : x ∈ Algebra.adjoin ℤ ({ζ} : Set K) := hy ▸ y.2
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hmem
  obtain ⟨f₀, hf₀⟩ := hmem
  have hmon : (cyclotomic m ℤ).Monic := cyclotomic.monic m ℤ
  have hcycdeg : (cyclotomic m ℤ).natDegree = m.totient := natDegree_cyclotomic m ℤ
  have hcycroot : aeval ζ (cyclotomic m ℤ) = 0 := by
    have : (cyclotomic m ℤ).map (algebraMap ℤ K) = cyclotomic m K := map_cyclotomic m _
    rw [aeval_def, eval₂_eq_eval_map, this]
    exact hζ.isRoot_cyclotomic (NeZero.pos m)
  refine ⟨f₀ %ₘ cyclotomic m ℤ, ?_, ?_⟩
  · have hne : cyclotomic m ℤ ≠ 1 := by
      intro h
      have h0 : (0 : ℕ) = m.totient := by rw [← hcycdeg, h, natDegree_one]
      exact (Nat.totient_pos.mpr (NeZero.pos m)).ne' h0.symm
    exact hcycdeg ▸ natDegree_modByMonic_lt f₀ hmon hne
  · have := modByMonic_add_div f₀ (cyclotomic m ℤ)
    calc aeval ζ (f₀ %ₘ cyclotomic m ℤ)
        = aeval ζ (f₀ %ₘ cyclotomic m ℤ + cyclotomic m ℤ * (f₀ /ₘ cyclotomic m ℤ)) := by
          rw [map_add, map_mul, hcycroot, zero_mul, add_zero]
      _ = x := by rw [this]; simpa using hf₀

omit [IsCyclotomicExtension {m} ℚ K] in
/-- Two rational polynomials of degree less than `φ m` taking the same value at `ζ` are
equal: this is uniqueness of the representation in the power basis of `ζ`. -/
lemma eq_of_aeval_eq {f g : ℚ[X]} (hf : f.natDegree < m.totient) (hg : g.natDegree < m.totient)
    (h : aeval ζ f = aeval ζ g) : f = g := by
  by_contra hne
  have hd : f - g ≠ 0 := sub_ne_zero.mpr hne
  have hroot : aeval ζ (f - g) = 0 := by rw [map_sub, h, sub_self]
  have hmin : cyclotomic m ℚ = minpoly ℚ ζ :=
    hζ.minpoly_eq_cyclotomic_of_irreducible (cyclotomic.irreducible_rat (NeZero.pos m))
  have hle : (minpoly ℚ ζ).degree ≤ (f - g).degree :=
    minpoly.degree_le_of_ne_zero ℚ ζ hd hroot
  rw [← hmin] at hle
  have hdeg : (cyclotomic m ℚ).natDegree = m.totient := natDegree_cyclotomic m ℚ
  have hlt : (f - g).natDegree < m.totient :=
    lt_of_le_of_lt (natDegree_sub_le f g) (by omega)
  have := natDegree_le_natDegree hle
  omega

variable (c) in
/-- **The coefficient step.**  If `p` has degree at most `N`, if `2 * N < φ m` and if
`p(ζ + c ζ⁻¹)` is an algebraic integer, then the top coefficient `p.coeff N` is an integer.

Indeed `ζ ^ N p(ζ + c ζ⁻¹) = (shiftPoly c N p)(ζ)` is an algebraic integer, so it is a
`ℤ`-polynomial in `ζ` of degree `< φ m`; since `shiftPoly c N p` also has degree `< φ m`
the two polynomials agree, and `p.coeff N` is the coefficient of `X ^ (2 * N)`. -/
lemma coeff_isInt_of_isIntegral {N : ℕ} (hN : 2 * N < m.totient) {p : ℚ[X]}
    (hp : p.natDegree < N + 1)
    (hint : IsIntegral ℤ (aeval (ζ + (c : K) * ζ⁻¹) p)) :
    ∃ z : ℤ, p.coeff N = (z : ℚ) := by
  have h1 : IsIntegral ℤ (ζ ^ N * aeval (ζ + (c : K) * ζ⁻¹) p) :=
    ((hζ.isIntegral (NeZero.pos m)).pow N).mul hint
  obtain ⟨f, hfdeg, hf⟩ := hζ.exists_intPoly_of_isIntegral h1
  have hmapdeg : (f.map (algebraMap ℤ ℚ)).natDegree = f.natDegree :=
    natDegree_map_eq_of_injective (algebraMap ℤ ℚ).injective_int f
  have h2 : aeval ζ (Monogenic.shiftPoly c N p) = aeval ζ (f.map (algebraMap ℤ ℚ)) := by
    rw [hζ.aeval_shiftPoly hp c, aeval_map_algebraMap, hf]
  have h3 : Monogenic.shiftPoly c N p = f.map (algebraMap ℤ ℚ) :=
    hζ.eq_of_aeval_eq
      (lt_of_le_of_lt (Monogenic.natDegree_shiftPoly_le c N p) hN) (by omega) h2
  refine ⟨f.coeff (2 * N), ?_⟩
  rw [← Monogenic.coeff_shiftPoly c N p, h3, coeff_map]
  simp

variable (c) in
/-- **The descent.**  A rational polynomial of degree at most `N`, with `2 * N < φ m`, taking
an algebraic integer value at `ζ + c ζ⁻¹` in fact has integer coefficients: strip off the top
coefficient, which is an integer by `coeff_isInt_of_isIntegral`, and induct. -/
lemma mem_adjoin_of_natDegree_lt : ∀ N : ℕ, 2 * N < m.totient → ∀ p : ℚ[X],
    p.natDegree < N + 1 → IsIntegral ℤ (aeval (ζ + (c : K) * ζ⁻¹) p) →
    aeval (ζ + (c : K) * ζ⁻¹) p ∈ Algebra.adjoin ℤ ({ζ + (c : K) * ζ⁻¹} : Set K) := by
  intro N
  induction N with
  | zero =>
    intro hN p hp hint
    obtain ⟨z, hz⟩ := hζ.coeff_isInt_of_isIntegral c hN hp hint
    have h0 : p.natDegree = 0 := Nat.lt_one_iff.mp hp
    rw [eq_C_of_natDegree_eq_zero h0, aeval_C, hz]
    have : (algebraMap ℚ K) ((z : ℚ)) = algebraMap ℤ K z := by
      rw [IsScalarTower.algebraMap_apply ℤ ℚ K]; norm_num
    rw [this]
    exact Subalgebra.algebraMap_mem _ z
  | succ N ih =>
    intro hN p hp hint
    obtain ⟨z, hz⟩ := hζ.coeff_isInt_of_isIntegral c hN hp hint
    set u : K := ζ + (c : K) * ζ⁻¹ with hu
    have hui : IsIntegral ℤ u := hζ.isIntegral_add_int_mul_inv c
    set q : ℚ[X] := p - C (p.coeff (N + 1)) * X ^ (N + 1) with hq
    have hqdeg : q.natDegree < N + 1 := by
      refine lt_of_le_of_lt (natDegree_le_iff_coeff_eq_zero.mpr fun i hi => ?_) (Nat.lt_succ_self N)
      rw [hq, coeff_sub, coeff_C_mul, coeff_X_pow]
      by_cases h : i = N + 1
      · subst h; simp
      · rw [if_neg h, mul_zero, sub_zero]
        exact coeff_eq_zero_of_natDegree_lt (by omega)
    have hval : aeval u q = aeval u p - (z : K) * u ^ (N + 1) := by
      rw [hq, map_sub, map_mul, map_pow, aeval_C, aeval_X, hz, map_intCast]
    have hintq : IsIntegral ℤ (aeval u q) := by
      rw [hval]
      exact hint.sub ((isIntegral_algebraMap (x := z)).mul (hui.pow _))
    have hmem := ih (by omega) q hqdeg hintq
    have hzmem : (z : K) ∈ Algebra.adjoin ℤ ({u} : Set K) := by
      have : (z : K) = algebraMap ℤ K z := by norm_num
      rw [this]; exact Subalgebra.algebraMap_mem _ z
    have humem : u ∈ Algebra.adjoin ℤ ({u} : Set K) :=
      Algebra.subset_adjoin (Set.mem_singleton u)
    have : aeval u p = aeval u q + (z : K) * u ^ (N + 1) := by rw [hval]; ring
    rw [this]
    exact Subalgebra.add_mem _ hmem (Subalgebra.mul_mem _ hzmem (Subalgebra.pow_mem _ humem _))

variable (c) in
/-- **The main theorem.**  If `ℚ(ζ + c ζ⁻¹)` is a *proper* subfield of the cyclotomic field
`K = ℚ(ζ)`, then every algebraic integer of `ℚ(ζ + c ζ⁻¹)` lies in `ℤ[ζ + c ζ⁻¹]`.

Together with the (trivial) reverse inclusion this says that the ring of integers of
`ℚ(ζ + c ζ⁻¹)` is `ℤ[ζ + c ζ⁻¹]`, so that field is monogenic. -/
theorem mem_adjoin_int_of_isIntegral (hne : ℚ⟮ζ + (c : K) * ζ⁻¹⟯ ≠ ⊤)
    {x : K} (hx : IsIntegral ℤ x) (hxmem : x ∈ ℚ⟮ζ + (c : K) * ζ⁻¹⟯) :
    x ∈ Algebra.adjoin ℤ ({ζ + (c : K) * ζ⁻¹} : Set K) := by
  have : NumberField K := IsCyclotomicExtension.numberField {m} ℚ K
  have huZ : IsIntegral ℤ (ζ + (c : K) * ζ⁻¹) := hζ.isIntegral_add_int_mul_inv c
  have huQ : IsIntegral ℚ (ζ + (c : K) * ζ⁻¹) := huZ.tower_top
  have htrank : finrank ℚ ℚ⟮ζ + (c : K) * ζ⁻¹⟯ = (minpoly ℚ (ζ + (c : K) * ζ⁻¹)).natDegree :=
    IntermediateField.adjoin.finrank huQ
  have hKrank : finrank ℚ K = m.totient :=
    IsCyclotomicExtension.finrank (n := m) K (cyclotomic.irreducible_rat (NeZero.pos m))
  have hdvd : (minpoly ℚ (ζ + (c : K) * ζ⁻¹)).natDegree ∣ m.totient := by
    rw [← htrank, ← hKrank]
    exact ⟨finrank ℚ⟮ζ + (c : K) * ζ⁻¹⟯ K, (finrank_mul_finrank ℚ _ K).symm⟩
  have htpos : 0 < (minpoly ℚ (ζ + (c : K) * ζ⁻¹)).natDegree := minpoly.natDegree_pos huQ
  have htne : (minpoly ℚ (ζ + (c : K) * ζ⁻¹)).natDegree ≠ m.totient := fun h =>
    hne (IntermediateField.eq_of_le_of_finrank_eq le_top (by rw [htrank, h, ← hKrank]; simp))
  -- properness of the subfield forces `2 * t ≤ φ m`
  have hle : 2 * (minpoly ℚ (ζ + (c : K) * ζ⁻¹)).natDegree ≤ m.totient := by
    obtain ⟨s, hs⟩ := hdvd
    have hs0 : s ≠ 0 := by
      rintro rfl
      rw [Nat.mul_zero] at hs
      exact (Nat.totient_pos.mpr (NeZero.pos m)).ne' hs
    have hs1 : s ≠ 1 := by rintro rfl; rw [Nat.mul_one] at hs; exact htne hs.symm
    calc 2 * (minpoly ℚ (ζ + (c : K) * ζ⁻¹)).natDegree
        ≤ s * (minpoly ℚ (ζ + (c : K) * ζ⁻¹)).natDegree :=
          Nat.mul_le_mul_right _ (by omega)
      _ = m.totient := by rw [hs, Nat.mul_comm]
  -- write `x` as a polynomial of degree `< t` in `ζ + c ζ⁻¹`
  have hxsub : x ∈ Algebra.adjoin ℚ ({ζ + (c : K) * ζ⁻¹} : Set K) := by
    have hx' : x ∈ ℚ⟮ζ + (c : K) * ζ⁻¹⟯.toSubalgebra := hxmem
    rwa [IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic huQ.isAlgebraic] at hx'
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hxsub
  obtain ⟨p₀, hp₀⟩ := hxsub
  have hmon : (minpoly ℚ (ζ + (c : K) * ζ⁻¹)).Monic := minpoly.monic huQ
  have hne1 : minpoly ℚ (ζ + (c : K) * ζ⁻¹) ≠ 1 := by
    intro h
    rw [h, natDegree_one] at htpos
    exact lt_irrefl 0 htpos
  have hmoddeg := natDegree_modByMonic_lt p₀ hmon hne1
  have heval : aeval (ζ + (c : K) * ζ⁻¹) (p₀ %ₘ minpoly ℚ (ζ + (c : K) * ζ⁻¹)) = x := by
    have hdiv := modByMonic_add_div p₀ (minpoly ℚ (ζ + (c : K) * ζ⁻¹))
    calc aeval (ζ + (c : K) * ζ⁻¹) (p₀ %ₘ minpoly ℚ (ζ + (c : K) * ζ⁻¹))
        = aeval (ζ + (c : K) * ζ⁻¹) (p₀ %ₘ minpoly ℚ (ζ + (c : K) * ζ⁻¹)
            + minpoly ℚ (ζ + (c : K) * ζ⁻¹) * (p₀ /ₘ minpoly ℚ (ζ + (c : K) * ζ⁻¹))) := by
          rw [map_add, map_mul, minpoly.aeval, zero_mul, add_zero]
      _ = x := by rw [hdiv]; simpa using hp₀
  have := hζ.mem_adjoin_of_natDegree_lt c ((minpoly ℚ (ζ + (c : K) * ζ⁻¹)).natDegree - 1)
    (by omega) (p₀ %ₘ minpoly ℚ (ζ + (c : K) * ζ⁻¹)) (by omega) (heval ▸ hx)
  rwa [heval] at this

end IsPrimitiveRoot

end

end
